services:
    wsse.security.authentication.provider:
        class:  %wsse.authentication.provider.class%
        arguments: ['', %kernel.cache_dir%/security/nonces]

    wsse.security.authentication.listener:
        class:  %wsse.authentication.listener.class%
        arguments: [@security.context, @security.authentication.manager]